# Generated by Django 3.2.8 on 2022-12-23 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('user_type', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('user_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_date', models.DateField()),
                ('item_price', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('new_id', models.AutoField(primary_key=True, serialize=False)),
                ('new_title', models.CharField(max_length=25)),
                ('new_date', models.DateField(auto_now_add=True)),
                ('new_image', models.CharField(max_length=500)),
                ('new_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='supplier', serialize=False, to='AppBack.account')),
                ('supplier_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user', serialize=False, to='AppBack.account')),
                ('user_type', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('sex', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=500)),
                ('item_price', models.IntegerField()),
                ('item_picture', models.CharField(max_length=1000)),
                ('item_description', models.CharField(max_length=1000)),
                ('item_url', models.CharField(max_length=1000)),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBack.type')),
                ('user_id', models.ForeignKey(max_length=25, on_delete=django.db.models.deletion.CASCADE, to='AppBack.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='History_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBack.history')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBack.item')),
            ],
            options={
                'unique_together': {('history_id', 'item_id')},
            },
        ),
    ]
