# Generated by Django 3.2.8 on 2022-12-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_picture',
            field=models.CharField(max_length=2000),
        ),
    ]
