# Generated by Django 3.2.8 on 2022-12-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBack', '0003_auto_20221223_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_date',
            field=models.DateField(null=True),
        ),
    ]
