# Generated by Django 4.1.1 on 2022-11-14 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBack', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='email',
        ),
    ]
