# Generated by Django 3.2.8 on 2022-11-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBack', '0002_remove_supplier_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_status',
            field=models.BooleanField(default=True),
        ),
    ]
