# Generated by Django 3.2.8 on 2022-12-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBack', '0002_alter_item_item_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_picture',
            field=models.CharField(max_length=1000),
        ),
    ]
