# Generated by Django 3.2.8 on 2022-12-17 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBack', '0002_alter_new_new_description'),
        ('AppBack', '0003_account_user_status'),
    ]

    operations = [
    ]
