# Generated by Django 4.1.4 on 2022-12-14 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBack', '0002_alter_new_new_description'),
        ('AppBack', '0003_account_user_status'),
    ]

    operations = [
    ]
