# Generated by Django 3.2.8 on 2022-12-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBack', '0004_merge_20221217_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_picture',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_url',
            field=models.CharField(max_length=1000),
        ),
    ]
