# Generated by Django 4.1.4 on 2022-12-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBack', '0004_merge_20221214_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='prueba',
            field=models.IntegerField(max_length=25, null=True),
        ),
    ]
