# Generated by Django 3.2.8 on 2022-12-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBack', '0005_alter_item_item_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='item_price',
            field=models.IntegerField(),
        ),
    ]
