# Generated by Django 3.2.8 on 2022-12-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBack', '0006_alter_item_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=200),
        ),
    ]
