# Generated by Django 3.2.8 on 2022-12-30 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBack', '0007_item_item_clic'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='item_clic',
            field=models.IntegerField(default=0),
        ),
    ]
